# Generated by Django 3.0.5 on 2021-04-21 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField()),
                ('categories', models.TextField()),
                ('content', models.TextField()),
                ('video_type', models.CharField(choices=[('YT', 'YouTube'), ('FB', 'Facebook'), ('OK', 'Одноклассники'), ('DM', 'Dailymotion'), ('VM', 'Vimeo')], default=1, max_length=255)),
                ('video_id', models.CharField(blank=True, max_length=255)),
                ('published_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
